# Generated by Django 5.0.6 on 2024-06-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Smart phone", "Smart phone"),
                    ("Tablets", "Tablets"),
                    ("Smart Watch", "Smart Watch"),
                    ("Laptop", "Laptop"),
                ],
                max_length=200,
            ),
        ),
    ]
