# Generated by Django 5.0.6 on 2024-06-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_cart_quantity_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.CharField(default="Order Placed", max_length=100),
        ),
    ]
